@ "test."
    - "test ''" fails
    - "test '.'" works
    - "test -d /" works
    - "test -e ./" works
    - "test -e '$HOME'" works
    - "test 2 = 2" works
    - "test 2 -lt 1" fails
    - "test 1 -le 1" works
    - "test 2 -gt 1" works
    - "test 3 -ge 1" works
